// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

final IOS_APIKEY = dotenv.env["IOS_APIKEY"]!;
final IOS_APPID = dotenv.env["IOS_APPID"]!;
final ANDROID_APIKEY = dotenv.env["ANDROID_APIKEY"]!;
final ANDROID_APPID = dotenv.env["ANDROID_APPID"]!;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: ANDROID_APIKEY!,
    appId: ANDROID_APPID!,
    messagingSenderId: '709718832158',
    projectId: 'mynotes-sticky-firebase',
    storageBucket: 'mynotes-sticky-firebase.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: IOS_APIKEY!,
    appId: IOS_APPID!,
    messagingSenderId: '709718832158',
    projectId: 'mynotes-sticky-firebase',
    storageBucket: 'mynotes-sticky-firebase.appspot.com',
    iosClientId: '709718832158-hc61id2mvl23qv8u4gevmsf7htjojpd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
